### ISSUE TITLE
Can not find "org.as3commons.collections.framework.IList"

### ISSUE THREAD

**Issue by ChitaGideon** [teotigraphix/as3-commons-asblocks#2]
I download all this project
 but cannot find this interface  int "org.as3commons.asblocks.ASFactory"

 Is there anything I miss?

**Comment by teotigraphix** [comment]
Hi
Check out http://www.as3commons.org/as3-commons-collections/index.html the IList should be located in the swc.

**Comment by ChitaGideon** [comment]
thanks
